export const profiles = [
  {
    id: 1,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/AnneAnderson.jpg",
    name: "Anne Anderson",
    position: "Student Services Coordinator",
    company: "Aarhus University",
    location: "Aarhus, Denmark",
    bio: `A student services coordinator at Aarhus University who has over a decade of experience in enhancing campus life for students with a strong commitment to innovation, ensuring that university resources are accessible and efficiently managed`,
    briefIdea: `A 24/7 booking platform for Aarhus University to reserve classrooms and facilities, with real-time availability and mobile access`,
    vision: `Passionate about streamlining processes and improving accessibility, I am spearheading the development of a user-friendly room-booking platform aimed at simplifying space reservation for students and faculty. This platform will feature real-time availability, seamless mobile integration, and an intuitive interface designed to eliminate scheduling conflicts and enhance user experience.`,
    hashtags: [
      "#EdTech",
      "#RoomBooking",
      "#UniversityPlatform",
      "#FacilityManagement",
      "#ProductivityTools",
      "#UserExperience",
      "#InnovationInEducation",
    ],
    requiredSkills: [
      "Frontend Development",
      "Backend Development",
      "UX/UI Design",
      "Project Management",
    ],
    requirements: [
      `Experience in React, Angular, or similar frameworks to build a user-friendly interface`,
      `Skills in database management and system architecture for real-time availability tracking`,
      `Expertise in designing intuitive booking flows, especially for mobile use`,
      `Knowledge of agile methodologies to ensure timely development and stakeholder communication`,
    ],
  },
  {
    id: 2,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/MadsMikkelsen.jpg",
    name: "Mads Mikkelsen",
    position: "Senior Agronomist",
    company: "United Farms Co.",
    location: "Copenhaghen, Denmark",
    bio: `An AI-powered crop monitoring and prediction platform designed for medium-to-large farms, offering real-time updates on soil health, weather patterns, and crop yield predictions`,
    briefIdea: `An AI-powered crop monitoring and prediction platform designed for medium-to-large farms, offering real-time updates on soil health, weather patterns, and crop yield predictions`,
    vision: `By combining my expertise in agronomy and the latest technological advancements, I aim to create an accessible platform that empowers farmers to make informed decisions, increasing productivity while reducing waste and costs. This platform will not only address day-to-day farming challenges but also enable better long-term planning through predictive insights. My ultimate goal is to contribute to global food security while promoting sustainable and eco-friendly farming practices.`,
    hashtags: [
      "#AgriTech",
      "#SmartFarming",
      "#AIForAgriculture",
      "#SustainableFarming",
      "#PrecisionAgriculture",
      "#DataAnalytics",
    ],
    requiredSkills: [
      "Data Science",
      "Machine Learning",
      "Frontend Development",
      "Cloud Computing",
    ],
    requirements: [
      `Experience with Python, TensorFlow, or PyTorch for building predictive models`,
      `Skills in React or Vue.js for creating an intuitive dashboard`,
      `Understanding of cloud platforms (AWS, Azure) for real-time data processing`,
      `Background in geospatial analysis or GIS technologies is a bonus`,
    ],
  },
  {
    id: 3,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/JohannePedersen.jpg",
    name: "Johanne Pedersen",
    position: "Head of Community Outreach",
    company: "Bright Future Nonprofit",
    location: "Viborg, Denmark",
    bio: `Leading community outreach initiatives at Bright Future, I’ve spent the past decade fostering meaningful connections between volunteers and nonprofits, ensuring that every act of kindness creates measurable impact.`,
    briefIdea: `A community-driven app that connects volunteers with local charities and initiatives, featuring personalized recommendations, impact tracking, and gamification to boost engagement`,
    vision: `My goal is to revolutionize how communities engage with local causes by creating a vibrant, user-friendly platform that simplifies volunteer matching and amplifies social good. By incorporating gamification and personalized recommendations, I envision a world where volunteering becomes a regular and rewarding part of everyone’s life. This platform will foster stronger, more connected communities, ensuring every effort contributes to meaningful, measurable change for both individuals and organizations.`,
    hashtags: [
      "#SocialImpact",
      "#VolunteerPlatform",
      "#CommunityEngagement",
      "#Gamification",
      "#ImpactTracking",
      "#NonprofitTech",
    ],
    requiredSkills: [
      "Mobile App Development",
      "Gamification Strategies",
      "UI/UX Design",
      "Social Media Integration",
    ],
    requirements: [
      `Proficiency in React Native or Flutter for cross-platform mobile app development`,
      `Experience in gamification techniques to boost user engagement`,
      `Ability to integrate social media APIs for easy sharing and sign-ups`,
      `Understanding of analytics to track user engagement and app effectiveness`,
    ],
  },
];
