export const profiles = [
  {
    id: 1,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/AnneAnderson.jpg",
    name: "Anne Anderson",
    position: "Student Services Coordinator",
    company: "Aarhus University",
    location: "Aarhus, Denmark",
    bio: `A student services coordinator at Aarhus University who has over a decade of experience in enhancing campus life for students with a strong commitment to innovation`,
    briefIdea: `A 24/7 booking platform for Aarhus University to reserve classrooms and facilities, with real-time availability and mobile access`,
    vision: `Passionate about streamlining processes and improving accessibility, I am spearheading the development of a user-friendly room-booking platform aimed at simplifying space reservation for students and faculty. This platform will feature real-time availability, seamless mobile integration, and an intuitive interface designed to eliminate scheduling conflicts and enhance user experience.`,
    hashtags: [
      "#EdTech",
      "#RoomBooking",
      "#FacilityManagement",
      "#ProductivityTools",
      "#InnovationInEducation",
    ],
    requiredSkills: [
      "Frontend Development",
      "Backend Development",
      "UX/UI Design",
      "Project Management",
    ],
    requirements: [
      `Experience in React, Angular, or similar frameworks to build a user-friendly interface`,
      `Skills in database management and system architecture for real-time availability tracking`,
      `Expertise in designing intuitive booking flows, especially for mobile use`,
      `Knowledge of agile methodologies to ensure timely development and stakeholder communication`,
    ],
  },
  {
    id: 2,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/MadsMikkelsen.jpg",
    name: "Mads Mikkelsen",
    position: "Senior Agronomist",
    company: "United Farms Co.",
    location: "Copenhaghen, Denmark",
    bio: `An AI-powered crop monitoring and prediction platform designed for medium-to-large farms, offering real-time updates on soil health, weather patterns, and crop yield predictions`,
    briefIdea: `An AI-powered crop monitoring and prediction platform designed for medium-to-large farms, offering real-time updates on soil health, weather patterns, and crop yield predictions`,
    vision: `By combining my expertise in agronomy and the latest technological advancements, I aim to create an accessible platform that empowers farmers to make informed decisions, increasing productivity while reducing waste and costs. This platform will not only address day-to-day farming challenges but also enable better long-term planning through predictive insights. My ultimate goal is to contribute to global food security while promoting sustainable and eco-friendly farming practices.`,
    hashtags: [
      "#AgriTech",
      "#SmartFarming",
      "#AIForAgriculture",
      "#SustainableFarming",
      "#PrecisionAgriculture",
      "#DataAnalytics",
    ],
    requiredSkills: [
      "Data Science",
      "Machine Learning",
      "Frontend Development",
      "Cloud Computing",
    ],
    requirements: [
      `Experience with Python, TensorFlow, or PyTorch for building predictive models`,
      `Skills in React or Vue.js for creating an intuitive dashboard`,
      `Understanding of cloud platforms (AWS, Azure) for real-time data processing`,
      `Background in geospatial analysis or GIS technologies is a bonus`,
    ],
  },
  {
    id: 3,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/JohannePedersen.jpg",
    name: "Johanne Pedersen",
    position: "Head of Community Outreach",
    company: "Bright Future Nonprofit",
    location: "Viborg, Denmark",
    bio: `I’ve spent the past decade fostering meaningful connections between volunteers and nonprofits, ensuring that every act of kindness creates measurable impact.`,
    briefIdea: `A community-driven app that connects volunteers with local charities and initiatives, featuring personalized recommendations, impact tracking, and gamification to boost engagement`,
    vision: `My goal is to revolutionize how communities engage with local causes by creating a vibrant, user-friendly platform that simplifies volunteer matching and amplifies social good. By incorporating gamification and personalized recommendations, I envision a world where volunteering becomes a regular and rewarding part of everyone’s life. This platform will foster stronger, more connected communities, ensuring every effort contributes to meaningful, measurable change for both individuals and organizations.`,
    hashtags: [
      "#SocialImpact",
      "#VolunteerPlatform",
      "#CommunityEngagement",
      "#Gamification",
    ],
    requiredSkills: [
      "Mobile App Development",
      "Gamification Strategies",
      "UI/UX Design",
    ],
    requirements: [
      `Proficiency in React Native or Flutter for cross-platform mobile app development`,
      `Experience in gamification techniques to boost user engagement`,
      `Ability to integrate social media APIs for easy sharing and sign-ups`,
      `Understanding of analytics to track user engagement and app effectiveness`,
    ],
  },
  {
    id: 4,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/JonasKarlsson.jpg",
    name: "Jonas Karlsson",
    position: "Logistics Manager",
    company: "Nordic Logistics",
    location: "Odense, Denmark",
    bio: `An experienced logistics manager with over 15 years in optimizing supply chains and warehouse management systems across Northern Europe.`,
    briefIdea: `Developing an AI-driven supply chain optimization tool to reduce costs and increase efficiency in logistics operations for medium-sized businesses.`,
    vision: `Leveraging my extensive background in logistics, I aim to create an AI-powered platform that provides real-time optimization suggestions for supply chain management. This tool will help businesses reduce operational costs, predict demand, and manage inventory more effectively, leading to streamlined operations and increased profitability.`,
    hashtags: [
      "#LogisticsTech",
      "#SupplyChain",
      "#AIinLogistics",
      "#OperationalEfficiency",
      "#InventoryManagement",
    ],
    requiredSkills: [
      "Artificial Intelligence",
      "Data Analytics",
      "Cloud Computing",
    ],
    requirements: [
      `Experience with AI algorithms relevant to logistics and supply chain management`,
      `Proficiency in backend technologies like Node.js or Python for robust system development`,
      `Ability to handle large datasets and perform predictive analytics`,
      `Knowledge of cloud platforms for scalable and reliable service delivery`,
    ],
  },
  {
    id: 5,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/SineSørensen.jpg",
    name: "Sine Sørensen",
    position: "Renewable Energy Consultant",
    company: "GreenTech Solutions",
    location: "Aalborg, Denmark",
    bio: `A renewable energy enthusiast dedicated to promoting sustainable solutions and reducing carbon footprints through innovative technologies.`,
    briefIdea: `An app that allows homeowners to monitor and optimize their energy consumption in real-time, integrating data from smart meters and renewable energy sources.`,
    vision: `My vision is to empower individuals to take control of their energy usage by providing a comprehensive platform that not only monitors consumption but also offers actionable insights and suggestions for energy optimization. By integrating data from various sources, the app will help users make informed decisions, reduce their carbon footprint, and contribute to a more sustainable future.`,
    hashtags: [
      "#RenewableEnergy",
      "#Sustainability",
      "#EnergyEfficiency",
      "#SmartHome",
      "#GreenTech",
    ],
    requiredSkills: ["Data Visualization", "IoT Integration", "UX/UI Design"],
    requirements: [
      `Experience in developing mobile applications for iOS and Android platforms`,
      `Skills in data visualization to present energy data in an intuitive way`,
      `Knowledge of IoT devices and smart meter integration`,
      `Ability to design user-friendly interfaces that encourage regular app engagement`,
    ],
  },
  {
    id: 6,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/NielsHansen.jpg",
    name: "Niels Hansen",
    position: "Cultural Heritage Specialist",
    company: "Denmark National Museum",
    location: "Copenhagen, Denmark",
    bio: `A dedicated cultural heritage professional with a passion for making history accessible through modern technology.`,
    briefIdea: `Creating an augmented reality (AR) app that brings historical sites to life, allowing users to experience Denmark's heritage in an immersive way.`,
    vision: `I aim to bridge the gap between history and technology by developing an AR platform that overlays historical events and structures onto present-day locations. This will enhance educational experiences and promote tourism by providing an interactive way to explore Denmark's rich cultural heritage.`,
    hashtags: [
      "#AugmentedReality",
      "#CulturalHeritage",
      "#EdTech",
      "#HistoricalPreservation",
      "#TourismInnovation",
    ],
    requiredSkills: [
      "AR Development",
      "3D Modeling",
      "App Development",
      "Graphic Design",
    ],
    requirements: [
      `Proficiency in AR platforms like ARKit or ARCore`,
      `Experience in 3D modeling and animation`,
      `Skills in app development for seamless AR integration`,
      `Creative graphic design abilities to create engaging visual content`,
    ],
  },
  {
    id: 7,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/KarenThomsen.jpg",
    name: "Karen Thomsen",
    position: "Wellness Coach",
    company: "Mindful Living",
    location: "Roskilde, Denmark",
    bio: `A wellness coach specializing in mindfulness and holistic health, with a mission to make wellness accessible to all.`,
    briefIdea: `Developing a personalized wellness app that offers meditation, yoga sessions, and mental health resources tailored to individual needs.`,
    vision: `I envision a world where mental and physical well-being are prioritized. By creating a personalized wellness app, I aim to provide users with tools and resources that fit their unique lifestyles, helping them achieve balance and improve overall health through mindfulness practices.`,
    hashtags: [
      "#WellnessTech",
      "#Mindfulness",
      "#MentalHealth",
      "#PersonalizedWellness",
      "#Yoga",
    ],
    requiredSkills: [
      "Mobile App Development",
      "Content Creation",
      "AI Personalization",
      "UX/UI Design",
    ],
    requirements: [
      `Experience in developing user-friendly mobile applications`,
      `Ability to integrate AI for personalized content recommendations`,
      `Skills in creating or curating wellness and mindfulness content`,
      `Expertise in designing intuitive interfaces that enhance user experience`,
    ],
  },
  {
    id: 8,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/AndersKristensen.jpg",
    name: "Anders Kristensen",
    position: "Financial Analyst",
    company: "Nordic Bank",
    location: "Esbjerg, Denmark",
    bio: `A financial analyst with a keen interest in fintech innovations and making financial services more accessible.`,
    briefIdea: `A peer-to-peer micro-lending platform that connects small businesses with individual investors, streamlining funding processes.`,
    vision: `My goal is to democratize access to funding for small businesses by creating a platform that simplifies the lending process. By connecting entrepreneurs directly with investors, we can foster economic growth and innovation, providing opportunities for both parties to benefit from mutually advantageous arrangements.`,
    hashtags: [
      "#FinTech",
      "#PeerToPeerLending",
      "#SmallBusiness",
      "#InvestmentPlatform",
      "#EconomicGrowth",
    ],
    requiredSkills: [
      "Blockchain Development",
      "Web Development",
      "Cybersecurity",
      "Regulatory Compliance",
    ],
    requirements: [
      `Experience in building secure and scalable web platforms`,
      `Knowledge of blockchain technology for transparent transactions`,
      `Expertise in cybersecurity to protect sensitive financial data`,
      `Understanding of financial regulations and compliance requirements`,
    ],
  },
  {
    id: 9,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/EmilieSorensen.jpg",
    name: "Emilie Sørensen",
    position: "Environmental Scientist",
    company: "EcoDynamics",
    location: "Helsingør, Denmark",
    bio: `An environmental scientist committed to combating climate change through innovative solutions and public engagement.`,
    briefIdea: `An interactive platform that tracks individual carbon footprints and offers actionable steps to reduce environmental impact.`,
    vision: `I believe that awareness is the first step toward change. By creating a platform that educates and empowers individuals to monitor and reduce their carbon footprints, we can collectively make a significant impact on the environment. The platform will provide personalized recommendations, challenges, and community support to encourage sustainable living.`,
    hashtags: [
      "#ClimateAction",
      "#Sustainability",
      "#CarbonFootprint",
      "#EnvironmentalAwareness",
      "#GreenLiving",
    ],
    requiredSkills: [
      "Web Development",
      "Data Analytics",
      "Behavioral Science",
      "UX/UI Design",
    ],
    requirements: [
      `Proficiency in web development languages and frameworks`,
      `Ability to analyze and interpret environmental data`,
      `Understanding of behavioral psychology to encourage user engagement`,
      `Design skills to create an intuitive and motivating user interface`,
    ],
  },
  {
    id: 10,
    type: "Idea Owner",
    profileImage: "/src/assets/avatar/MikkelOlsen.jpg",
    name: "Mikkel Olsen",
    position: "E-commerce Specialist",
    company: "Global Marketplaces",
    location: "Kolding, Denmark",
    bio: `An e-commerce expert with a passion for leveraging technology to enhance online shopping experiences.`,
    briefIdea: `Developing a virtual reality (VR) shopping platform that allows users to browse and purchase products in a virtual mall environment.`,
    vision: `I aim to revolutionize the online shopping experience by combining e-commerce with virtual reality technology. This platform will provide users with an immersive and interactive shopping environment, bridging the gap between physical and online retail. By enhancing customer engagement, we can drive sales and create new opportunities for retailers.`,
    hashtags: [
      "#Ecommerce",
      "#VirtualReality",
      "#RetailInnovation",
      "#CustomerExperience",
      "#VRShopping",
    ],
    requiredSkills: [
      "VR Development",
      "3D Modeling",
      "E-commerce Integration",
      "Backend Development",
    ],
    requirements: [
      `Experience with VR technologies and development tools`,
      `Skills in 3D modeling to create realistic virtual environments`,
      `Ability to integrate e-commerce platforms and payment gateways`,
      `Strong backend development skills to manage user data and transactions securely`,
    ],
  },
];
